# Generated by Django 4.2.16 on 2024-11-12 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Не указано')], default='O', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название заявки')),
                ('description', models.TextField(max_length=150, verbose_name='Описание заявки')),
                ('image', models.FileField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'), verbose_name='Загрузите фото заявки')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('D', 'Выполнено')], default='N', max_length=1, verbose_name='Статус заявки')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата создания заявки')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.category', verbose_name='Категория заявки')),
            ],
        ),
    ]
