# Generated by Django 4.2.16 on 2024-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('L', 'Лофт'), ('M', 'Минимализм'), ('K', 'Классицизм'), ('A', 'Арт-деко'), ('H', 'Хай-тек'), ('O', 'Не указано')], default='O', help_text='Название категории', max_length=1),
        ),
    ]
