# Generated by Django 4.2.16 on 2024-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_alter_application_category_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории', max_length=150, verbose_name='Категория'),
        ),
    ]
