# Generated by Django 4.2.16 on 2024-11-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_alter_application_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Загрузите фото заявки'),
        ),
    ]
