# Generated by Django 4.2.16 on 2024-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_alter_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке'),
        ),
    ]
