# Generated by Django 4.2.16 on 2024-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='done_status_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото готового дизайна'),
        ),
    ]
