# Generated by Django 4.2.16 on 2024-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_alter_application_done_status_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Добавить в избранное'),
        ),
    ]
